export type Named={_id:string;name:string;color?:string};export type User=Named&{email:string;avatar?:string;role:{name:string;permissions:string[]}};export type Metadata={stages:(Named&{sequence:number;probability:number;folded:boolean;isWon:boolean})[];users:User[];teams:Named[];tags:Named[];sources:Named[];campaigns:Named[];mediums:Named[];lostReasons:Named[];activityTypes:(Named&{icon?:string;defaultDays?:number})[]};export type Opportunity={_id:string;id:string;title:string;company?:Named;contact?:Named;email?:string;phone?:string;expectedRevenue:number;recurringRevenue:number;probability:number;priority:number;salesperson?:User;salesTeam?:Named;stage:Named;tags:Named[];source?:Named;campaign?:Named;medium?:Named;expectedClosingDate?:string;status:'open'|'won'|'lost';kanbanOrder:number;internalNotes?:string;timeline?:Timeline[];activities?:Activity[]};export type Lead={_id:string;title:string;contactName?:string;companyName?:string;email?:string;phone?:string;expectedRevenue:number;priority:number;salesperson?:User;salesTeam?:Named;source?:Named;campaign?:Named;tags:Named[];status:string;converted:boolean;convertedOpportunity?:{_id:string;stage?:Named};score:number;scoreReasons?:{label:string;points:number}[];scoreRecommendation?:string;hot?:boolean;channel?:Named;touchCount:number;createdAt:string;city?:string;notes?:string;medium?:Named;lostReason?:Named;lostNotes?:string;lastTouchedAt?:string;updatedAt?:string;timeline?:Timeline[];activities?:Activity[];deal?:LeadDeal|null};
// The opportunity a converted lead became, as GET /leads/:id returns it - enough to draw the
// deal's position in the pipeline on the lead's own screen.
export type LeadDeal={_id:string;title:string;expectedRevenue:number;probability:number;status:'open'|'won'|'lost';stage?:Named&{sequence:number;probability:number;isWon:boolean};expectedClosingDate?:string};
export type ChannelType='website_form'|'landing_page'|'whatsapp'|'facebook'|'instagram'|'google_ads'|'email'|'chatbot'|'api'|'csv_import'|'phone_call';
export type IntakeChannel=Named&{channelType:ChannelType;source?:Named;medium?:Named;campaign?:Named;salesTeam?:Named;active:boolean;keyPreview:string;lastUsedAt?:string;createdAt:string;apiKey?:string};// Every activity is logged against one primary record (relatedModel/relatedId) but the server's
// Activity Engine also resolves and stores the full relationship web it belongs to - lead,
// contact, company, deal, campaign, salesperson - so any screen can show or filter by any of them.
export type Activity={_id:string;summary:string;notes?:string;dueDate:string;status:string;completedAt?:string;activityType:Named;assignedTo:User;relatedModel:string;relatedId:string;lead?:{_id:string;title:string};contact?:Named;company?:Named;opportunity?:{_id:string;title:string};campaign?:Named;salesperson?:User;direction?:'outbound'|'inbound';durationMinutes?:number;body?:string;amount?:number};export type Timeline={_id:string;eventType:string;message:string;createdAt:string;createdBy:User};export type Paged<T>={data:T[];pagination:{page:number;limit:number;total:number;pages:number}};
// One row of GET /reports/source-attribution: a source's full funnel (leads in, customers out)
// plus what it cost to run and the ROI that bought - roi/costPerCustomer are null until the
// source has a monthlySpend set in Configuration, so spend-less sources don't get ranked as if
// they were free.
export type SourceAttribution={_id:string;name:string;leads:number;customers:number;revenue:number;spend:number;conversionRate:number;costPerCustomer:number|null;roi:number|null};
