import{useQuery}from'@tanstack/react-query';import{useNavigate}from'react-router-dom';import{api,money}from'../lib/api';import{useAuth}from'../context/Auth';import{PageHeader}from'../components/Shell';import{Loading}from'../components/ui';import{Area,AreaChart,Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';import{AlertTriangle,BadgeDollarSign,CheckCircle2,Clock3,Flame,Funnel,Sparkles,Target}from'lucide-react';import ManagerDashboard from'./ManagerDashboard';
type Data={summary:{total:number;expectedRevenue:number;wonRevenue:number;won:number;lost:number;conversionRate:number;activitiesToday:number;activitiesOverdue:number};pipeline:{_id:string;value:number;count:number}[];monthly:{_id:string;value:number}[]};
type Priority={_id:string;title:string;company?:string;probability:number;expectedRevenue:number;overdueDays:number;daysStuck:number;reason:string};
type Briefing={hotLeads:number;overdueFollowUps:number;meetingsToday:number;pipelineValue:number;priorities:Priority[]};
function greeting(){const h=new Date().getHours();return h<12?'Good morning':h<17?'Good afternoon':'Good evening'}
export default function Dashboard(){const{user}=useAuth();if(user&&['Administrator','Sales Manager'].includes(user.role.name))return <ManagerDashboard/>;return <RepDashboard/>}
function RepDashboard(){const{user}=useAuth();const nav=useNavigate();const{data,isLoading}=useQuery({queryKey:['dashboard'],queryFn:()=>api<Data>('/dashboard')});const{data:brief}=useQuery({queryKey:['dashboard','briefing'],queryFn:()=>api<Briefing>('/dashboard/briefing')});if(isLoading)return <Loading/>;const s=data!.summary;const cards=[['Opportunities',s.total,Funnel],['Expected revenue',money(s.expectedRevenue),BadgeDollarSign],['Won revenue',money(s.wonRevenue),CheckCircle2],['Conversion',`${s.conversionRate}%`,Target],['Due today',s.activitiesToday,Clock3],['Overdue',s.activitiesOverdue,AlertTriangle]] as const;
const first=user?.name?.split(' ')[0];
const stats=brief?[['🔥','Hot leads',brief.hotLeads],['⚠️','Overdue follow-ups',brief.overdueFollowUps],['📅','Meetings today',brief.meetingsToday],['💰',' Pipeline',money(brief.pipelineValue)]] as const:null;
return <><PageHeader title="Sales Overview" subtitle="Live pipeline and activity performance"/><div className="p-4">
<section className="panel mb-4 overflow-hidden bg-gradient-to-br from-sky-600 to-indigo-700 p-5 text-white">
<div className="flex items-center gap-2 text-sm font-medium text-sky-100"><Sparkles size={16}/><span>AI Sales Assistant</span></div>
<h1 className="mt-1 text-xl font-semibold">{greeting()}{first?`, ${first}`:''} 👋</h1>
{stats&&<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{stats.map(([icon,label,value])=><div key={label} className="rounded-lg bg-white/10 p-3"><div className="text-xs text-sky-100">{icon} {label}</div><div className="mt-1 text-lg font-semibold">{value}</div></div>)}</div>}
{brief&&<div className="mt-5">
<div className="mb-2 text-xs font-semibold uppercase tracking-wide text-sky-100">AI Priorities</div>
{brief.priorities.length===0?<p className="text-sm text-sky-100">Nothing urgent right now — the pipeline is under control.</p>:
<ol className="space-y-2">{brief.priorities.map((p,i)=><li key={p._id} onClick={()=>nav(`/opportunities/${p._id}`)} className="flex cursor-pointer items-center justify-between gap-3 rounded-lg bg-white/10 p-3 transition hover:bg-white/20">
<div className="flex items-center gap-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-white/20 text-xs font-semibold">{i+1}</span>
<div><div className="font-medium">{p.title}{p.company?<span className="font-normal text-sky-100"> · {p.company}</span>:null}</div>
<div className="flex items-center gap-1 text-xs text-sky-100">{p.overdueDays>0?<AlertTriangle size={12}/>:p.daysStuck>=7?<Clock3 size={12}/>:<Flame size={12}/>}<span>{p.reason}</span></div></div></div>
<div className="shrink-0 text-right text-xs text-sky-100"><div className="text-sm font-semibold text-white">{p.probability}%</div>win prob.</div>
</li>)}</ol>}
</div>}
</section>
<div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{cards.map(([label,value,Icon])=><div className="panel p-3" key={label}><div className="flex items-center justify-between text-xs text-slate-500"><span>{label}</span>{Icon&&<Icon size={16}/>}</div><div className="mt-2 text-xl font-semibold">{value}</div></div>)}</div>
<div className="mt-4 grid gap-4 lg:grid-cols-2"><Chart title="Pipeline revenue"><ResponsiveContainer width="100%" height={280}><BarChart data={data!.pipeline}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="_id" fontSize={11}/><YAxis fontSize={11}/><Tooltip formatter={v=>money(Number(v))}/><Bar dataKey="value" fill="#0284c7" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></Chart><Chart title="Monthly won revenue"><ResponsiveContainer width="100%" height={280}><AreaChart data={data!.monthly}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#0284c7" stopOpacity={.3}/><stop offset="95%" stopColor="#0284c7" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="_id" fontSize={11}/><YAxis fontSize={11}/><Tooltip formatter={v=>money(Number(v))}/><Area dataKey="value" stroke="#0284c7" fill="url(#fill)"/></AreaChart></ResponsiveContainer></Chart></div></div></>}
function Chart({title,children}:{title:string;children:React.ReactNode}){return <section className="panel p-4"><h2 className="mb-3 text-sm font-semibold">{title}</h2>{children}</section>}
