import{useState}from'react';import{useQuery}from'@tanstack/react-query';import{api,money}from'../lib/api';import type{SourceAttribution}from'../lib/types';import{PageHeader}from'../components/Shell';import{Loading}from'../components/ui';import{Bar,BarChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
export default function Reporting(){const[dimension,setDimension]=useState('stage');const[measure,setMeasure]=useState('expectedRevenue');const[type,setType]=useState('bar');const q=useQuery({queryKey:['report',dimension,measure],queryFn:()=>api<{_id:string;value:number;count:number}[]>(`/reports?dimension=${dimension}&measure=${measure}`)});return <><PageHeader title="Reporting"><select className="field w-40" value={dimension} onChange={e=>setDimension(e.target.value)}>{['stage','salesperson','salesTeam','source','campaign','month','lostReason'].map(x=><option key={x}>{x}</option>)}</select><select className="field w-40" value={measure} onChange={e=>setMeasure(e.target.value)}><option value="expectedRevenue">Expected revenue</option><option value="proratedRevenue">Prorated revenue</option><option value="probability">Probability</option><option value="count">Opportunity count</option></select><select className="field w-24" value={type} onChange={e=>setType(e.target.value)}><option value="bar">Bar</option><option value="pie">Pie</option><option value="table">Table</option></select></PageHeader>{q.isLoading?<Loading/>:<div className="space-y-4 p-4"><div className="panel p-4">{type==='table'?<table className="w-full text-left text-sm"><thead><tr><th className="p-2">Dimension</th><th>Value</th><th>Count</th></tr></thead><tbody>{q.data!.map(x=><tr className="border-t" key={x._id}><td className="p-2">{x._id??'Unassigned'}</td><td>{measure==='count'?x.value:money(x.value)}</td><td>{x.count}</td></tr>)}</tbody></table>:<ResponsiveContainer width="100%" height={430}>{type==='pie'?<PieChart><Pie data={q.data} dataKey="value" nameKey="_id" outerRadius={160} label>{q.data!.map((_,i)=><Cell fill={['#0284c7','#38bdf8','#3b82f6','#10b981','#f59e0b'][i%5]} key={i}/>)}</Pie><Tooltip/></PieChart>:<BarChart data={q.data}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="_id"/><YAxis/><Tooltip/><Bar dataKey="value" fill="#0284c7"/></BarChart>}</ResponsiveContainer>}</div><SourceAttributionPanel/></div>}</>}

// Lead Source Attribution: leads → customers → ROI per source, ranked by ROI so the top row is
// literally the answer to "where should we spend next month". Sources with no monthlySpend set
// (in Configuration) show ROI as "—" rather than being sorted as if they were infinitely
// profitable or excluded outright.
function SourceAttributionPanel(){
  const q=useQuery({queryKey:['source-attribution'],queryFn:()=>api<SourceAttribution[]>('/reports/source-attribution')});
  if(q.isLoading)return <Loading/>;
  const rows=[...(q.data??[])].sort((a,b)=>(b.roi??-Infinity)-(a.roi??-Infinity));
  const best=rows.find(r=>r.roi!==null);
  return <div className="panel overflow-hidden">
    <div className="border-b bg-slate-50 px-4 py-3"><h2 className="text-sm font-semibold">Lead Source Attribution & ROI</h2><p className="text-xs text-slate-500">{best?<>Best return right now: <b>{best.name}</b> at {best.roi}% ROI. Set a monthly spend per source in Configuration to rank the rest.</>:'Set a monthly spend per source in Configuration to see ROI here.'}</p></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b text-xs text-slate-500"><tr><th className="p-2">Source</th><th>Leads</th><th>Customers</th><th>Conversion</th><th>Spend / mo</th><th>Revenue won</th><th>Cost / customer</th><th>ROI</th></tr></thead><tbody>{rows.map(r=><tr className="border-t" key={r._id}><td className="p-2 font-semibold">{r.name}</td><td>{r.leads}</td><td>{r.customers}</td><td>{r.conversionRate}%</td><td>{money(r.spend)}</td><td>{money(r.revenue)}</td><td>{r.costPerCustomer!==null?money(r.costPerCustomer):'—'}</td><td className={r.roi===null?'':r.roi>=0?'font-semibold text-emerald-600':'font-semibold text-red-600'}>{r.roi!==null?`${r.roi}%`:'—'}</td></tr>)}{!rows.length&&<tr><td className="p-4 text-slate-400" colSpan={8}>No lead sources configured yet.</td></tr>}</tbody></table></div>
  </div>;
}
