import { useMutation,useQuery } from '@tanstack/react-query';
import { Bot,Mail,Phone,Plus,ShieldCheck,Sparkles } from 'lucide-react';
import { WhatsAppIcon } from "../components/WhatsAppIcon";
import { api,date } from '../lib/api';
import { PageHeader } from '../components/Shell';
import { Button,Empty,Loading } from '../components/ui';

type Communication={_id:string;channel:'email'|'whatsapp'|'call';direction:string;status:string;subject?:string;body?:string;sender?:string;recipient?:string;createdAt:string};
export function Inbox(){const q=useQuery({queryKey:['communications'],queryFn:()=>api<Communication[]>('/communications')});return <><PageHeader title="Inbox" subtitle="Customer communication across configured providers"><Button disabled title="Configure a provider before sending"><Plus size={15}/>Compose</Button></PageHeader><ProviderNotice/><div className="p-4 sm:p-6">{q.isLoading?<Loading/>:q.data?.length?<div className="panel overflow-hidden">{q.data.map(item=><div className="flex items-center gap-4 border-b p-4 last:border-0" key={item._id}><ChannelIcon channel={item.channel}/><div className="min-w-0 flex-1"><div className="flex gap-2"><b className="truncate text-sm">{item.subject||item.body||`${item.channel} activity`}</b><span className="badge bg-slate-100 capitalize text-slate-600">{item.status}</span></div><p className="truncate text-xs text-slate-500">{item.direction==='inbound'?item.sender:item.recipient} · {date(item.createdAt)}</p></div></div>)}</div>:<div className="panel"><Empty title="No conversations yet" detail="Connect an email or WhatsApp provider to send and receive messages."/></div>}</div></>}
function ProviderNotice(){return <div className="flex gap-3 border-b border-blue-200 bg-blue-50 px-4 py-3 text-xs text-blue-800 sm:px-6"><ShieldCheck className="shrink-0" size={18}/><div><b>Provider setup required</b><p className="mt-0.5 text-blue-700">No external messages are sent until an administrator configures a server-side provider.</p></div></div>}
function ChannelIcon({channel}:{channel:string}){const Icon=channel==='email'?Mail:channel==='whatsapp'?WhatsAppIcon:Phone;return <span className="grid h-10 w-10 place-items-center rounded-lg bg-indigo-50 text-indigo-600"><Icon size={18}/></span>}


type AIStatus={configured:boolean;provider:string;model:string};type ActionPlan={overview:string;priorities:{title:string;reason:string;action:string;urgency:'high'|'medium'|'low'}[];generatedAt:string};
export function AIAssistant(){const status=useQuery({queryKey:['ai-status'],queryFn:()=>api<AIStatus>('/ai/status')});const plan=useMutation({mutationFn:()=>api<ActionPlan>('/ai/action-plan',{method:'POST'})});const ready=status.data?.configured;return <><PageHeader title="AI Assistant" subtitle="Grounded sales suggestions based only on CRM data"><span className={`badge ${ready?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{ready?'OpenRouter connected':'Setup required'}</span></PageHeader><div className="mx-auto max-w-5xl p-4 sm:p-6"><div className="panel overflow-hidden"><div className="border-b bg-indigo-50 p-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-indigo-600 text-white"><Sparkles size={20}/></span><h2 className="mt-4 text-lg font-semibold">OpenRouter sales copilot</h2><p className="mt-1 max-w-2xl text-sm text-slate-500">Uses only CRM records visible to you. Suggestions remain separate from stored customer facts.</p><p className="mt-2 text-xs text-slate-400">Model: {status.data?.model??'openrouter/free'}</p></div>{!ready&&!status.isLoading&&<div className="border-b border-amber-200 bg-amber-50 p-4 text-xs text-amber-800">Add <b>OPENROUTER_API_KEY</b> to server/.env and restart the API.</div>}<div className="p-6"><Button className="btn-primary" disabled={!ready||plan.isPending} onClick={()=>plan.mutate()}><Sparkles size={15}/>{plan.isPending?'Building action plan…':'Generate today’s action plan'}</Button>{plan.isError&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-xs text-red-700">{plan.error.message}</p>}{plan.data&&<div className="mt-6"><h3 className="font-semibold">Today’s plan</h3><p className="mt-1 text-sm text-slate-600">{plan.data.overview}</p><div className="mt-4 grid gap-3">{plan.data.priorities.map((item,index)=><article className="rounded-xl border p-4" key={`${item.title}-${index}`}><div className="flex items-center gap-2"><span className="grid h-6 w-6 place-items-center rounded-full bg-blue-50 text-xs font-semibold text-blue-700">{index+1}</span><b className="text-sm">{item.title}</b><span className={`badge ml-auto ${item.urgency==='high'?'bg-red-50 text-red-700':item.urgency==='medium'?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700'}`}>{item.urgency}</span></div><p className="mt-2 text-xs text-slate-500">{item.reason}</p><p className="mt-2 text-sm font-medium text-blue-700">{item.action}</p></article>)}</div></div>}</div></div></div></>}
